### ISSUE TITLE
collins08.csv data cleaning and meanrankshift trouble shooting

### ISSUE THREAD

**Issue by laurenmh** [laurenmh/codyn#37]
The collins08.csv has multiple entries for the species asclvird in all years and replicates, and for the species desmilli in the unburned replicate for years 1994 and 1998. This is causing an indexing error because all our functions require unique abundance values for a species within a year and replicate. 

Syd - want to have a look at the collins08.csv and figure out the data cleaning issue? Note that I moved it to the inst/extdata folder 

Even when I select years with unique values, this aspect of the meanrank code gives me trouble with collins08.csv but not kn_001d.csv, still trouble shooting:
    commonspp <- Map(getintersect, y1, y2, dataname = species)

**Comment by SydJones** [comment]
Hi Lauren,

The below data cleaning issues are fixed.

Syd

**Comment by laurenmh** [comment]
Thanks Syd! Can you double check you pushed them? Change isn't coming through.

**Comment by SydJones** [comment]
Can you see the changes now?

**Comment by laurenmh** [comment]
yep! thanks. still having problems with getintersect on that dataset, for
the life of me can't figure out, not an issue with column names and when i
vectorized the species column and check it with intersect it works fine...

**Comment by laurenmh** [comment]
oh nvm getintersect was dependent on columns being in a certain order, fixing it now. think the rest of the  meanrankshift is looking okay but that's what testing is for ;)
